import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: ["./src/index.ts"],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false,
  sourcemap: 'external',
  external: [
  "fs",
  "path",
  "http",
  "https",
  "crypto",
  "node:fs",
  "node:path",
  "node:http",
  "node:https",
  "node:crypto",
  "node:stream",
  "node:buffer",
  "node:util",
  "node:events",
  "node:url",
  "bun:test",
  "dotenv",
  "zod",
  "@elizaos/core",
  "@elizaos/plugin-sql",
  "@elizaos/plugin-message-handling",
  "@elizaos/plugin-agentkit",
  "@elizaos/plugin-evm",
  "@elizaos/plugin-solana",
  "@elizaos/plugin-secrets-manager",
  "@elizaos/plugin-trust",
  "@elizaos/plugin-tasks"
],
  naming: '[dir]/[name].[ext]',
};