packages:
    - "docs"
    - "packages/core"
    - "packages/cli"
    - "packages/adapter-postgres"
    - "packages/client-auto"
    - "packages/client-direct"
    - "packages/client-discord"
    - "packages/client-farcaster"
    - "packages/client-lens"
    - "packages/client-telegram"
    - "packages/client-telegram-account"
    - "packages/client-twitter"
    - "packages/client-instagram"
    - "packages/client-slack"
    - "packages/client-alexa"
    - "packages/client-simsai"
    - "packages/plugin-bootstrap"
    - "packages/plugin-node"
    - "packages/plugin-di"
    - "packages/plugin-image-generation"
    - "packages/plugin-video-generation"
    - "packages/plugin-web-search"
    - "packages/client-xmtp"
    - "packages/client-deva"
    - "packages/plugin-sgx"
    - "packages/plugin-tee"
    - "packages/plugin-tee-log"
    - "packages/plugin-tee-verifiable-log"
    - "packages/plugin-email"
    - "packages/plugin-email-automation"
    - "client"
    - "agent"
