/**
 * TESTING INFRASTRUCTURE MIGRATION STEPS
 * 
 * Responsibilities:
 * - Delete V1 test structure (__tests__ directory)
 * - Create V2 test structure (src/test/ directory)
 * - Generate test utilities and placeholder tests
 * - Manage test file naming conventions
 */

import { logger } from '@elizaos/core';
import * as fs from 'fs-extra';
import * as path from 'node:path';
import type { MigrationContext, StepResult } from '../types.js';

export class TestingSteps {
  private context: MigrationContext;

  constructor(context: MigrationContext) {
    this.context = context;
  }

  /**
   * Delete V1 test structure
   */
  async deleteV1Tests(ctx: MigrationContext): Promise<StepResult> {
    const testsDir = path.join(ctx.repoPath, '__tests__');
    if (await fs.pathExists(testsDir)) {
      await fs.remove(testsDir);
      return {
        success: true,
        message: 'Deleted V1 __tests__ directory',
        changes: ['__tests__/'],
      };
    }

    return {
      success: true,
      message: 'No V1 tests directory found',
    };
  }

  /**
   * Create V2 test structure with utils.ts and placeholder test.ts
   */
  async createV2Tests(ctx: MigrationContext): Promise<StepResult> {
    const testDir = path.join(ctx.repoPath, 'src', 'test');
    await fs.ensureDir(testDir);

    // Import test templates
    const { UTILS_TS_EXACT_CONTENT } = await import('../test-templates/index.js');

    // Create utils.ts with exact content from template
    const utilsPath = path.join(testDir, 'utils.ts');
    await fs.writeFile(utilsPath, UTILS_TS_EXACT_CONTENT);
    logger.info('✅ Created src/test/utils.ts with exact template content');

    ctx.changedFiles.add('src/test/utils.ts');

    // CRITICAL: Create placeholder test.ts to ensure correct filename
    // The real content will be generated by Claude, but this ensures the right filename exists
    const testPath = path.join(testDir, 'test.ts'); // NOT test.test.ts
    const placeholderTest = `// Placeholder - will be generated by migration system
import type { TestSuite } from "@elizaos/core";

export const test: TestSuite = {
  name: "${ctx.pluginName} tests",
  tests: []
};

export default test;`;
    
    await fs.writeFile(testPath, placeholderTest);
    logger.info('✅ Created src/test/test.ts placeholder (will be filled by test generator)');
    ctx.changedFiles.add('src/test/test.ts');

    logger.info('📝 Test suite content will be generated after migration completes');

    return {
      success: true,
      message: 'Created V2 test infrastructure (utils.ts)',
      changes: ['src/test/utils.ts'],
      warnings: ['Comprehensive test suite will be generated after migration completes'],
    };
  }
} 