export const USER_NAME = 'user';
export const CHAT_SOURCE = 'client_chat';
export const GROUP_CHAT_SOURCE = 'client_group_chat';

export const AVATAR_IMAGE_MAX_SIZE = 300;

export enum FIELD_REQUIREMENT_TYPE {
  REQUIRED = 'required',
  OPTIONAL = 'optional',
}

export const FIELD_REQUIREMENTS: Record<CharacterFieldName, FieldRequirement> = {
  name: FIELD_REQUIREMENT_TYPE.REQUIRED,
  username: FIELD_REQUIREMENT_TYPE.OPTIONAL,
  system: FIELD_REQUIREMENT_TYPE.OPTIONAL,
  bio: FIELD_REQUIREMENT_TYPE.REQUIRED,
  topics: FIELD_REQUIREMENT_TYPE.OPTIONAL,
  knowledge: FIELD_REQUIREMENT_TYPE.OPTIONAL,
  messageExamples: FIELD_REQUIREMENT_TYPE.OPTIONAL,
  postExamples: FIELD_REQUIREMENT_TYPE.OPTIONAL,
  style: FIELD_REQUIREMENT_TYPE.OPTIONAL,
  plugins: FIELD_REQUIREMENT_TYPE.OPTIONAL,
  settings: FIELD_REQUIREMENT_TYPE.OPTIONAL,
};
