import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: ['./src/index.ts', './src/test-runner.ts'],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false,
  sourcemap: 'external',
  external: [
    'fs',
    'path',
    'http',
    'https',
    'crypto',
    'node:fs',
    'node:path',
    'node:http',
    'node:https',
    'node:crypto',
    'node:stream',
    'node:buffer',
    'node:util',
    'node:events',
    'node:url',
    'bun:test',
    'dotenv',
    'zod',
    '@elizaos/core',
    '@elizaos/server',
    '@elizaos/plugin-sql',
    '@elizaos/plugin-github',
    '@elizaos/plugin-todo',
    '@elizaos/plugin-trust',
    '@elizaos/plugin-rolodex',
    '@elizaos/plugin-planning',
    '@elizaos/plugin-research',
    '@elizaos/plugin-knowledge',
    '@elizaos/plugin-solana',
    '@elizaos/plugin-evm',
    '@elizaos/plugin-payment',
    '@elizaos/plugin-secrets-manager',
    '@elizaos/plugin-plugin-manager',
    '@elizaos/plugin-stagehand',
    '@elizaos/plugin-agentkit',
    '@elizaos/plugin-autocoder',
    '@elizaos/plugin-auton8n',
    '@elizaos/plugin-autonomy',
    '@elizaos/plugin-goals',
    '@elizaos/plugin-mcp',
    '@elizaos/plugin-ngrok',
    '@elizaos/plugin-tasks',
    'ssh2',
    'cpu-features',
  ],
  naming: '[dir]/[name].[ext]',
};
