import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        background: "var(--background)",
        "background-hover": "var(--background-hover)",
        "background-dark": "var(--background-dark)",
        "background-hover-dark": "var(--background-hover-dark)",
        sidebar: "var(--sidebar)",
        "typography-strong": "var(--typography-strong)",
        "typography-weak": "var(--typography-weak)",
        "typography-strong-dark": "var(--typography-strong-dark)",
        "typography-weak-dark": "var(--typography-weak-dark)",
        hover: "var(--hover)",
        fill: "var(--fill)",
        "fill-hover": "var(--fill-hover)",
        "fill-solid": "var(--fill-solid)",
        "stroke-strong": "var(--stroke-strong)",
        "stroke-medium": "var(--stroke-medium)",
        "stroke-weak": "var(--stroke-weak)",
        "stroke-weak-dark": "var(--stroke-weak-dark)",
        brand: "var(--brand)",
        "brand-hover": "var(--brand-hover)",
        "brand-stroke-strong": "var(--brand-stroke-strong)",
        "brand-stroke-weak": "var(--brand-stroke-weak)",
        "brand-fill": "var(--brand-fill)",
        "brand-text": "var(--brand-text)",
        "brand-dark": "var(--brand-dark)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-stroke-strong": "var(--accent-stroke-strong)",
        "accent-stroke-weak": "var(--accent-stroke-weak)",
        "accent-fill": "var(--accent-fill)",
        "accent-text": "var(--accent-text)",
        "accent-dark": "var(--accent-dark)",
        error: "var(--error)",
        "error-dark": "var(--error-dark)",
        "error-stroke-strong": "var(--error-stroke-strong)",
        "error-stroke-weak": "var(--error-stroke-weak)",
        "error-fill": "var(--error-fill)",
        warning: "var(--warning)",
        "warning-stroke-strong": "var(--warning-stroke-strong)",
        "warning-stroke-weak": "var(--warning-stroke-weak)",
        "warning-fill": "var(--warning-fill)",
        success: "var(--success)",
        "success-stroke-strong": "var(--success-stroke-strong)",
        "success-stroke-weak": "var(--success-stroke-weak)",
        "success-fill": "var(--success-fill)",
        info: "var(--info)",
        "info-stroke-strong": "var(--info-stroke-strong)",
        "info-stroke-weak": "var(--info-stroke-weak)",
        "info-fill": "var(--info-fill)",
        "focus-ring": "var(--focus-ring)",
        "focus-ring-dark": "var(--focus-ring-dark)",
        secondary: "var(--secondary)",
        "secondary-stroke-strong": "var(--secondary-stroke-strong)",
        "secondary-stroke-weak": "var(--secondary-stroke-weak)",
        "secondary-fill": "var(--secondary-fill)",
        "secondary-typography-strong": "var(--secondary-typography-strong)",
        "secondary-typography-strong-dark":
          "var(--secondary-typography-strong-dark)",
        "secondary-typography-weak": "var(--secondary-typography-weak)",
        "secondary-typography-weak-dark":
          "var(--secondary-typography-weak-dark)",
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-error",
    "bg-error-fill",
    "text-error",
    "border-error-stroke-strong",
    "border-error-stroke-weak",
    "bg-warning",
    "bg-warning-fill",
    "text-warning",
    "border-warning-stroke-strong",
    "border-warning-stroke-weak",
    "bg-success",
    "bg-success-fill",
    "text-success",
    "border-success-stroke-strong",
    "border-success-stroke-weak",
    "bg-info",
    "bg-info-fill",
    "text-info",
    "border-info-stroke-strong",
    "border-info-stroke-weak",
    "bg-brand",
    "bg-brand-fill",
    "text-brand",
    "border-brand-stroke-weak",
    "border-brand-stroke-strong",
    "bg-secondary",
    "bg-secondary-fill",
    "text-secondary",
    "border-secondary-stroke-strong",
    "border-secondary-stroke-weak",
    "text-secondary-typography-strong",
    "text-secondary-typography-strong-dark",
    "text-secondary-typography-weak",
    "text-secondary-typography-weak-dark",
    "btn-destructive",
  ],
};
export default config;
