import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: ["./src/index.ts"],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false,
  sourcemap: 'external',
  external: [
  "fs",
  "path",
  "http",
  "https",
  "crypto",
  "node:fs",
  "node:path",
  "node:http",
  "node:https",
  "node:crypto",
  "node:stream",
  "node:buffer",
  "node:util",
  "node:events",
  "node:url",
  "bun:test",
  "dotenv",
  "zod",
  "@elizaos/core",
  "@solana/web3.js",
  "@solana/spl-token",
  "react",
  "react-dom",
  "@tanstack/react-query",
  "bignumber.js",
  "bs58",
  "util",
  "stream",
  "buffer",
  "assert",
  "node:assert",
  "combined-stream",
  "form-data",
  "proxy-from-env",
  "url",
  "follow-redirects"
],
  naming: '[dir]/[name].[ext]',
};