import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  outDir: 'dist',
  sourcemap: true,
  clean: true,
  format: ['esm'],
  dts: true,
  external: [
    '@elizaos/core',
    '@solana/web3.js',
    '@solana/spl-token',
    'react',
    'react-dom',
    '@tanstack/react-query',
    'bignumber.js',
    'bs58',
    'zod',
    'dotenv',
    'util',
    'stream',
    'buffer',
    'crypto',
    'fs',
    'path',
    'assert',
    'node:assert',
    'node:url',
    'node:path',
    'combined-stream',
    'form-data',
    'proxy-from-env',
    'url',
    'follow-redirects',
  ],
  noExternal: ['./src'],
  platform: 'node',
  shims: true,
});
