import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: ["./src/index.ts"],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false,
  sourcemap: 'external',
  external: [
  "fs",
  "path",
  "http",
  "https",
  "crypto",
  "node:fs",
  "node:path",
  "node:http",
  "node:https",
  "node:crypto",
  "node:stream",
  "node:buffer",
  "node:util",
  "node:events",
  "node:url",
  "bun:test",
  "dotenv",
  "zod",
  "@elizaos/core",
  "@elizaos/plugin-message-handling",
  "@elizaos/plugin-discord",
  "@elizaos/plugin-knowledge",
  "@elizaos/plugin-telegram",
  "@elizaos/plugin-ngrok",
  "vitest",
  "// Externalize vitest to prevent bundling\n    @vitest/coverage-v8",
  "@vitest/runner",
  "@vitest/ui",
  "vite",
  "express",
  "helmet",
  "cors",
  "nanoid",
  "puppeteer",
  "cookie-parser",
  "express-session",
  "isomorphic-dompurify",
  "// Runtime modules that should be external\n    node:assert",
  "node:process"
],
  naming: '[dir]/[name].[ext]',
};