import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: ["./src/index.ts"],
  outdir: './dist',
  target: 'node',
  format: 'cjs',
  splitting: false,
  sourcemap: 'external',
  external: [
  "fs",
  "path",
  "http",
  "https",
  "crypto",
  "node:fs",
  "node:path",
  "node:http",
  "node:https",
  "node:crypto",
  "node:stream",
  "node:buffer",
  "node:util",
  "node:events",
  "node:url",
  "bun:test",
  "dotenv",
  "zod",
  "@elizaos/core",
  "uuid",
  "playwright",
  "playwright-core",
  "electron",
  "chromium-bidi",
  "axios",
  "cheerio",
  "duck-duck-scrape",
  "lru-cache",
  "pdf-parse",
  "@types/pdf-parse"
],
  naming: '[dir]/[name].[ext]',
};