import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: [
    './src/index.ts', 
    './src/bun-sqlite/adapter.ts',
    // Add schema entrypoints to ensure they're built as separate modules
    './src/schema/index.ts',
    './src/schema/agent.ts',
    './src/schema/cache.ts',
    './src/schema/channel.ts',
    './src/schema/channelParticipant.ts',
    './src/schema/component.ts',
    './src/schema/embedding.ts',
    './src/schema/entity.ts',
    './src/schema/log.ts',
    './src/schema/memory.ts',
    './src/schema/message.ts',
    './src/schema/messageServer.ts',
    './src/schema/participant.ts',
    './src/schema/relationship.ts',
    './src/schema/room.ts',
    './src/schema/serverAgent.ts',
    './src/schema/tasks.ts',
    './src/schema/world.ts',
  ],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false, // Disable splitting to ensure schema files are built individually
  sourcemap: 'external',
  external: [
    'fs',
    'path',
    'http',
    'https',
    'crypto',
    'node:fs',
    'node:path',
    'node:http',
    'node:https',
    'node:crypto',
    'node:stream',
    'node:buffer',
    'node:util',
    'node:events',
    'node:url',
    'bun:test',
    'bun:sqlite',
    'dotenv',
    'zod',
    '@elizaos/core',
    'playwright',
    'playwright-core',
    '@stagehand/web',
    'electron',
    'chromium-bidi',
  ],
  naming: '[dir]/[name].[ext]',
};
