import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: ['./src/index.ts'],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false,
  sourcemap: 'external',
  external: [
    'fs',
    'path',
    'http',
    'https',
    'crypto',
    'node:fs',
    'node:path',
    'node:http',
    'node:https',
    'node:crypto',
    'node:stream',
    'node:buffer',
    'node:util',
    'node:events',
    'node:url',
    'bun:test',
    'dotenv',
    'zod',
    '@elizaos/core',
    '@elizaos/plugin-sql',
    'uuid',
    'path-is-absolute',
    'mammoth',
    'textract',
    'jsdom',
    'pdfjs-dist',
    'multer',
    'react',
    'react-dom',
    'react-router-dom',
    'lucide-react',
    'clsx',
    'tailwind-merge',
    'ai',
    '@ai-sdk/anthropic',
    '@ai-sdk/google',
    '@ai-sdk/openai',
    '@openrouter/ai-sdk-provider',
  ],
  naming: '[dir]/[name].[ext]',
};
