import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: ['./src/index.ts', './src/test-utils/index.ts'],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false,
  sourcemap: 'external',
  external: [
    'fs',
    'path',
    'child_process',
    'os',
    'net',
    'tls',
    'dns',
    'readline',
    'zlib',
    'vm',
    'cluster',
    'process',
    'crypto',
    'buffer',
    'crypto-browserify',
    'js-sha1',
    'node:crypto',
    'node:buffer',
    'node:fs',
    'node:path',
    'node:web',
    'node:child_process',
    'node:os',
    'node:module',
    'sharp',
    'pino-pretty',
    'dotenv',
    '@solana/web3.js',
    'zod',
    '@hapi/shot',
    '@elizaos/core',
    'bun:test',
    'handlebars',
  ],
  naming: '[dir]/[name].[ext]',
};