import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: ['./src/index.ts'],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false,
  sourcemap: 'external',
  external: [
    'fs',
    'path',
    'http',
    'https',
    'crypto',
    'node:fs',
    'node:path',
    'node:http',
    'node:https',
    'node:crypto',
    'node:stream',
    'node:buffer',
    'node:util',
    'node:events',
    'node:url',
    'bun:test',
    'dotenv',
    'zod',
    'typescript',
    'execa',
    'fs-extra',
    'child_process',
    'stream',
    'util',
    'os',
    'url',
    '@elizaos/core',
    'punycode',
    'node-fetch',
    'agentkeepalive',
    'chromium-bidi',
    'cpu-features',
  ],
  naming: '[dir]/[name].[ext]',
};
