import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: [
    './src/index.ts',
    './src/commands/agent/actions/index.ts',
    './src/commands/agent/index.ts',
    './src/commands/auth/index.ts',
    './src/commands/create/index.ts',
    './src/commands/create/actions/index.ts',
    './src/commands/shared/index.ts',
    './src/commands/scenario/index.ts',
    './src/commands/scenario/generate.ts',
    './src/commands/scenario/run-scenario.ts',
    './src/commands/scenario/ActionTracker.ts',
    './src/commands/plugins/index.ts',
    './src/commands/start/index.ts',
    './src/commands/test/index.ts',
    './src/commands/update/index.ts',
    './src/commands/env/index.ts',
    './src/commands/cleanup/index.ts',
    './src/commands/benchmark.ts',
    './src/commands/test-production-verification.ts',
    './src/commands/stress-test-verification.ts',
    './src/commands/publish.ts',
    './src/scenarios-plugin.ts',
    './src/scenario-runner/index.ts',
    './src/scenario-runner/types.ts',
  ],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false,
  sourcemap: 'external',
  minify: false,
  external: [
    // Core node modules
    'fs',
    'path',
    'http',
    'https',
    'crypto',
    'node:fs',
    'node:path',
    'node:http',
    'node:https',
    'node:crypto',
    'node:stream',
    'node:buffer',
    'node:util',
    'node:events',
    'node:url',
    'node:child_process',
    'node:net',
    'node:os',
    'node:process',
    'node:string_decoder',
    'node:module',
    'bun:test',
    // Dependencies
    '@elizaos/core',
    '@elizaos/server',
    '@elizaos/client',
    '@elizaos/plugin-sql',
    '@elizaos/plugin-github',
    '@elizaos/plugin-todo',
    '@elizaos/plugin-trust',
    '@elizaos/plugin-rolodex',
    '@elizaos/plugin-planning',
    '@elizaos/plugin-research',
    '@elizaos/plugin-knowledge',
    '@elizaos/plugin-solana',
    '@elizaos/plugin-evm',
    '@elizaos/plugin-payment',
    '@elizaos/plugin-secrets-manager',
    '@elizaos/plugin-plugin-manager',
    '@elizaos/plugin-stagehand',
    '@elizaos/plugin-agentkit',
    '@elizaos/plugin-autocoder',
    '@elizaos/plugin-auton8n',
    '@elizaos/plugin-autonomy',
    '@elizaos/plugin-goals',
    '@elizaos/plugin-mcp',
    '@elizaos/plugin-ngrok',
    '@elizaos/plugin-tasks',
    '@elizaos/plugin-openai',
    // Other dependencies
    'dotenv',
    'zod',
    'fs-extra',
    'keytar',
    '@clack/prompts',
    'commander',
    'chokidar',
    'execa',
    'globby',
    'https-proxy-agent',
    'inquirer',
    'open',
    'ora',
    'rimraf',
    'semver',
    'simple-git',
    'tiktoken',
    'tsconfig-paths',
    'type-fest',
    'yoctocolors',
    '@anthropic-ai/sdk',
    'react',
    'react-dom',
  ],
  naming: '[dir]/[name].[ext]',
};
