import type { BuildConfig } from 'bun';

export const buildConfig: BuildConfig = {
  entrypoints: ["./src/index.ts"],
  outdir: './dist',
  target: 'node',
  format: 'esm',
  splitting: false,
  sourcemap: 'external',
  external: [
    "fs",
    "path",
    "http",
    "https",
    "crypto",
    "node:fs",
    "node:path",
    "node:http",
    "node:https",
    "node:crypto",
    "node:stream",
    "node:buffer",
    "node:util",
    "node:events",
    "node:url",
    "bun:test",
    "dotenv",
    "zod",
    "@elizaos/core",
    "serialport",
    "roslib",
    // Externalize problematic dependencies to prevent bundling
    "mock-aws-s3",
    "aws-sdk",
    "nock",
    "@mapbox/node-pre-gyp",
    // Externalize TensorFlow.js packages to prevent bundling issues
    "@tensorflow/tfjs-node",
    "@tensorflow/tfjs-core",
    "@tensorflow-models/coco-ssd",
    "@tensorflow-models/posenet",
    // Externalize other heavy dependencies
    "canvas",
    "sharp",
    "face-api.js",
    "tesseract.js",
    "onnxruntime-node",
    "ws",
    "mqtt",
    "axios"
  ],
  naming: '[dir]/[name].[ext]',
};